spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waste_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


# port settings
server:
  port: 8100
